import Head from "next/head";
import Header from "./components/Header";
import Image from "next/image";
import logo from "./assets/reactjs.png";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className="xcontainer">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.main}>
          <Header />
          <h1 className={styles.title}>Home Page</h1>
          <Image src={logo} />
        </div>
      </main>
    </div>
  );
}
